Task_1_1_2
dromankin/OOP pull request #2
Opened 2024-09-13 06:04 UTC by dromankin

2024-09-16 05:25 UTC, galinabykova requested changes
мягкий дедлайн засчитан, однако не затягивай с правками, чтобы посмотреть код внимательнее, мне нужно, чтобы ты сделал его в ООП стиле. Сейчас у тебя классы используются как структуры, ты позволяешь классам получать поля друг друга. Переделай это, но не просто, оборачивая поля геттерами-сеттерами, а продумав, какое поведение должно быть у того или иного класса

2024-09-16 05:25 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/romankin/Card.java
> +    public Card(String rank, String suit, int value) {
очки это внутреннее свойство карты, мне кажется, логичнее было бы высчитывать их тут, но можешь попробовать убедить меня в обратном

2024-09-16 05:25 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/romankin/Card.java
> +    protected int value;
почему protected?

2024-09-16 05:25 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/romankin/Deck.java
> +    ArrayList<Card> list;
обычно стараются не давать доступ к полям напрямую, лучше оборачивать их в геттеры-сеттеры, ведь поле - деталь реализации, а абстракции должны зависеть от поведения друг друга
https://javarush.com/groups/posts/1928-getterih-i-setterih
При этом нужно аккуратно подходить к этому вопросу и не делать геттеры и сеттеры ради геттеров и сеттеров, в которых протекает реализация абстракции протекает
https://www.yegor256.com/2014/09/16/getters-and-setters-are-evil.html

2024-09-17 16:04 UTC, dromankin commented on Task_1_1_2/src/main/java/ru/nsu/romankin/Card.java
> +    public Card(String rank, String suit, int value) {
Т.е. очки должны передаваться не в конструкторе, а устанавливаться в зависимости от ранга карты?

2024-09-17 16:13 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/romankin/Card.java
> +    public Card(String rank, String suit, int value) {
ага

2024-09-21 05:15 UTC, galinabykova requested changes

2024-09-21 05:15 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/romankin/Card.java
> +    boolean hidden = false; //this flag is showing if card hidden or not
не нужно давать доступ к полям в других классах

2024-09-21 05:15 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/romankin/Deck.java
> +    ArrayList<Card> list = new ArrayList<>();
не нужно давать доступ к этому полю из других классов. Если тебе нужно посмотреть первую карту или узнать, сколько карт в колоде, сделай соответствующие методы

2024-09-21 05:15 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/romankin/Main.java
> +public class Main {
этот класс написан в структурной парадигме, тут все методы и поля статические, причём у меня нет ощущения, что этот static оправдан. Ты получишь тот же результат, если сделаешь все поля и все методы, кроме main, нестатическими, и создашь экземпляр этого класса в main.
Синглтоны в Java делают иначе

2024-09-21 05:15 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/romankin/Player.java
> +    boolean hidden;
private

2024-09-21 05:15 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/romankin/Rank.java
> +    int value;
сделай поля private и доступ к ним через геттеры

2024-09-22 05:47 UTC, galinabykova requested changes

2024-09-22 05:47 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/romankin/Main.java
> +    private static final int blackjack = 21;
это константа, в нашем стиле кода нужно именовать большими буквами с прочерками для разделения слов

2024-09-22 05:47 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/romankin/MainTest.java
> +        assertTrue(main.playerWonRounds == 2);
если можно, лучше использовать AssertEquals

2024-09-22 05:47 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/romankin/MainTest.java
> +        assertTrue(true);
это искусственный тест, проверь хотя бы, что в выводе (который возвращает runGame) содержится что-то осмысленное

2024-09-22 13:33 UTC, galinabykova approved these changes

2024-09-22 13:43 UTC, merged