Task_1_1_3
dromankin/OOP pull request #3
Opened 2024-09-28 14:00 UTC by dromankin

2024-09-28 18:58 UTC, galinabykova requested changes
не забудь сделать парсер и тесты

2024-09-28 18:58 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/romankin/Expression.java
> +    protected Expression left;
мне кажется, это поле не стоит делать тут, потому что оно есть не у всех выражений. Предлагаю либо перенести в Add, Div и т.д., либо сделать класс для биноминальных выражений (то есть будет такая иерархия Выражения - Биноминальные выражения - Сложение)

2024-09-28 18:58 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/romankin/Variable.java
> +        int start = 0;
мне кажется, не очень хорошо, что ты протаскиваешь строку вплоть до переменной и парсишь её тут. Если в выражении будет тысяча переменных, ты тысячу раз будешь парсить словарь. Мне кажется, более удобно было бы сделать так:

в Expression сделать абстрактный метод evaluate(Map<String,String>)
переопределить его во всех наследниках
написать в Expression метод evaluate(String), в котором мы парсим строку в словарь и вызвать evaluate(Map<String,String>)
Тогда парсинг будет происходить единожды.
Предлагаю тебе либо переделать так код, либо доказать, что у твоего решения есть плюсы в сравнении с предложенным мной

2024-09-28 18:58 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/romankin/Variable.java
> +    public int eval(String string) {
а что будет происходить, если в твоём словаре нет нужно переменной?

2024-09-29 09:37 UTC, dromankin commented on Task_1_1_3/src/main/java/ru/nsu/romankin/Expression.java
> +    protected Expression left;
А мягкий дедлайн засчитан?

2024-09-29 13:44 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/romankin/Expression.java
> +    protected Expression left;
Ага

2024-10-02 09:33 UTC, galinabykova requested changes

2024-10-02 09:33 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/romankin/Expression.java
> +    public Map<String, String> eval_parse(String string) {
нужно ещё добавить метод, чтобы это работало "из коробки"
```java
public int eval(String s) {
    eval(eval_parse(s));
}
```

2024-10-02 09:33 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/romankin/Variable.java
> +    public int eval(Map<String, String> map) {
здесь происходит что-то странное. Ты бросаешь исключение и сразу же его ловишь и бросаешь другое исключение. Подозреваю, что try-catch throw RuntimeException тебе посоветовала idea, но тут не очень хорошая идея использовать его. Если решил делать исключения, предлагаю почитать про них. Я ожидаю, что у тебя либо будет бросаться RuntimeException и ты сможешь пояснить, почему RuntimeException, либо в этом методе появится throwsException в сигнатуре

2024-10-02 09:33 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/romankin/Variable.java
> +    public int eval(Map<String, String> map) {
то есть надо почитать про RuntimeException (непроверяемые исключения) и общие правила работы с исключениями

2024-10-03 08:29 UTC, galinabykova approved these changes

2024-10-03 19:09 UTC, merged