Task_1_2_1
dromankin/OOP pull request #4
Opened 2024-10-13 19:59 UTC by dromankin

2024-10-14 05:00 UTC, galinabykova requested changes
мягкий засчитан, жду полной реализации)

2024-10-14 05:00 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/romankin/TopologicalSort.java
> +    private List<Vertex<T>> ans = new ArrayList<>();
мне кажется, тут у тебя поля - не состояние объекта, их можно было бы как входные параметры передать в dfs

2024-10-14 05:00 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/romankin/TopologicalSort.java
> +    private List<Vertex<T>> ans = new ArrayList<>();
нет такого, что этот объект должен жить какое-то время и его состояние будет меняться в зависимости от действий пользователя

2024-10-14 05:00 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/romankin/Graph.java
> +    int getVertexId(Vertex<T> vertex);
почему ты решил сделать такой интерфейс? Он довольно специфичный, поэтому спрашиваю. Если есть причины (например, оптимизация) - ок, если просто так получилось, подумай об удобстве пользователя - будет ли ему удобно брать id, а потом работать с ним. Если да, прокомментируй это, если нет - нужно исправить. Мне не нравится, что пользователю приходится думать об id, которые дополнительная абстракция и деталь твоей реализации

2024-10-20 04:56 UTC, galinabykova requested changes

2024-10-20 04:56 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/romankin/TopologicalSort.java
> +    public List<Vertex<T>> topologicalSort(Graph<T> graph) {
static

2024-10-20 04:56 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/romankin/TopologicalSort.java
> +    private void dfs(int v, Graph<T> graph, boolean[] used, List<Vertex<T>> ans) {
static

2024-10-20 04:56 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/romankin/AdjacencyList.java
> +package ru.nsu.romankin;
в след раз добавляй в конец что-то про саму лабу, например, ru.nsu.romankin.graph

2024-10-20 04:56 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/romankin/Graph.java
> +        Scanner scanner = new Scanner(file);
нужно закрыть) удобно через try with recources

2024-10-20 04:56 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/romankin/Graph.java
> +                            addVertex(new Vertex<T>((T) Integer.valueOf(string)));
сделай на этот метод тест, в котором будешь читать граф с не строковой вершиной, скорее всего, тут будет ошибка, надо придумать, что с этим делать

2024-10-20 09:54 UTC, dromankin commented on Task_1_2_1/src/main/java/ru/nsu/romankin/Graph.java
> +        Scanner scanner = new Scanner(file);
А файл нельзя разве закрыть просто через scanner.close()?

2024-10-20 09:59 UTC, dromankin commented on Task_1_2_1/src/main/java/ru/nsu/romankin/Graph.java
> +        Scanner scanner = new Scanner(file);
Или в try with resources мы ловим исключение если файл неудачно закрылся?

2024-10-20 13:02 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/romankin/Graph.java
> +        Scanner scanner = new Scanner(file);
можно, но, если будет брошено исключение, до строчки с закрытием кода исполнение просто не дойдёт( можно закрыть в блоке finally, который исполнится даже если будет брошено исключение, но при закрытии тоже могут быть исключения, и в итоге получается монструозная конструкция. Поэтому лучше использовать try with recources.  Посмотри тут https://javarush.com/quests/lectures/questsyntaxpro.level15.lecture00 пункты 2 и 3

2024-10-20 15:28 UTC, galinabykova approved these changes

2024-10-20 15:29 UTC, merged