Add first version of hashtable
dromankin/OOP pull request #5
Opened 2024-10-26 08:18 UTC by dromankin

2024-10-26 17:26 UTC, galinabykova requested changes
мягкий засчитан

2024-10-26 17:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/romankin/hashtable/HashTable.java
> +public class HashTable <K, V> {
этот класс должен реализовывать интерфейс  Iterable

2024-10-26 17:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/romankin/hashtable/HashTable.java
> +        String res = "";
используй StringBuilder. String иммутабельный (неизменяемый) тип и каждый раз, когда ты  делаешь res += "something", строка res полностью копируется

2024-10-26 17:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/romankin/hashtable/HashTable.java
> +            for (int i = listIndex; i < table.size(); i++) {
вот тут не поняла, почему у тебя нет проверки на nodeIndex. Объясни, если я не разобралась, или исправь, если что-то тут не так)

2024-10-26 17:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/romankin/hashtable/HashTable.java
> +    public boolean equals(HashTable<K, V> compareTable) {
лучше переопределить equals из Object, потому что это стандартный метод и его используют другие структуры и алгоритмы (у тебя другая сигнатура (не тот входной параметр), не определён hashcode и нет override). Если считаешь, что перегрузка оправдана, объясни

2024-10-30 10:03 UTC, dromankin commented on Task_1_2_2/src/main/java/ru/nsu/romankin/hashtable/HashTable.java
> +            for (int i = listIndex; i < table.size(); i++) {
Не совсем понимаю, зачем нужна проверка на nodeIndex, если он конструктором всегда задаётся нулевым, а в цикле его значение либо зануляется при достижении конца ArrayList по некоторому хэшу, либо устанавливается равным индексу следующего элемента в ArrayList по некоторому хэшу, т.е. nodeIndex не может вылезти за размеры отдельных ArrayList'ов

2024-10-31 05:57 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/romankin/hashtable/HashTable.java
> +            for (int i = listIndex; i < table.size(); i++) {
@dromankin, криво сформулировала, я имела ввиду проверку наличия следующего элемента в текущем связном списке. Например, как будет работать твоя программа, если в последнем бакете (table.get(table.size() - 1)) будут элементы? Кажется, что всегда hasNext будет возвращать true

2024-10-31 06:01 UTC, galinabykova requested changes

2024-10-31 06:01 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/romankin/hashtable/HashTable.java
> +    public boolean equals(Object obj) {
сделай тест, в котором будут сравниваться хэш-таблицы с разными типами, то есть HashTable<K1, V1>  и HashTable<K2,V2>, где K1!=K2 и V1!=V2

2024-10-31 06:52 UTC, dromankin commented on Task_1_2_2/src/main/java/ru/nsu/romankin/hashtable/HashTable.java
> +            for (int i = listIndex; i < table.size(); i++) {
<img width="956" alt="Без имени" src="https://github.com/user-attachments/assets/7325d30a-f32a-443a-967f-931a46805036">

2024-10-31 07:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/romankin/hashtable/HashTable.java
> +            for (int i = listIndex; i < table.size(); i++) {
а, я поняла, у тебя индекс указывает на следующий элемент

2024-10-31 07:04 UTC, galinabykova requested changes

2024-10-31 07:04 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/romankin/hashtable/HashTable.java
> +        HashTable<K, V> compareTable = (HashTable<K, V>) obj;
тут, мне кажется, лучше использовать wildcard <?,?>

2024-10-31 07:04 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/romankin/hashtable/HashTable.java
> +        HashTable<K, V> compareTable = (HashTable<K, V>) obj;
потому что не факт, что у это хэш-таблички нужный тебе тип

2024-10-31 07:04 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/romankin/hashtable/HashTable.java
> +    public boolean equals(Object obj) {
сделай тест, в котором будешь сравнивать HashTable<Integer, Integer>, и  HashTable<String,String> и при необходимости переделай этот метод так, чтобы в этом случае он возвращал ложь

2024-11-02 15:51 UTC, galinabykova approved these changes

2024-11-02 16:09 UTC, merged